MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "https://cloudstor.aarnet.edu.au/plus/s/xtixKaxLWmbcyf7/download#mobilenet_v2-ecbe2b5.pth"
  BACKBONE:
    CONV_BODY: "MNV2-FPN-RETINANET"
    FREEZE_CONV_BODY_AT: 0
  RESNETS:
    BACKBONE_OUT_CHANNELS: 128
  USE_SYNCBN: True
  RPN_ONLY: True
  FCOS_ON: True
  FCOS_MASK: True
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    CENTER_SAMPLE: True
    POS_RADIUS: 1.5
    LOC_LOSS_TYPE: "giou"
    INFERENCE_TH: 0.03
    NUM_CONVS: 2 #defualt 4
  ROI_HEADS:
    USE_FPN: True
  MASK_ON: True
  ROI_MASK_HEAD:
    CONV_LAYERS: (128, 128)
    POOLER_SCALES: (0.125, 0.0625, 0.03125) # 1/8, 1/16, 1/32
    FEATURE_EXTRACTOR: "MaskRCNNFPNSpatialAttentionFeatureExtractor"
    LEVEL_MAP_FUNCTION: "CenterMaskLevelMapFunc"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  ROI_MASKIOU_HEAD:
    CONV_LAYERS: (128, 128)
DATASETS:
  TRAIN: ("coco_2020_train", "coco_2020_val")
  TEST:  ("coco_2020_val",)
INPUT:
  MIN_SIZE_RANGE_TRAIN: (580, 600)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1024
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (140000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 2
  WARMUP_METHOD: "constant"
OUTPUT_DIR : 'checkpoints/CenterMask-Lite-M-v2-FPN-res600-ms-bs32-1x'
